### PR TITLE
Many Many new features :)

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Hej @skuro, 

here is the first basic modification I made to the org plugin

- restructure the project `src/main/java, et caetera`
- spell checkying support

I might then add live template next. (then refresh my lexing/parsing ^^)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Some more things now:
In a nutshell:
- LiveTemplates
- Todo indexer
- Commenter
- Syntax highlight for line code, and keywords `X+something`
- improved doc

**Comment by AdrieanKhisbe** [comment]
better support for block :)
(I decided to keep the 0.2 for now, as long as it's not merged and published)

**Comment by skuro** [comment]
Wooooo, that's what I call a contribution! I will take some time to double check your changes, and then happily merge them into the master branch. Thanks for being awesome ;-)

**Comment by AdrieanKhisbe** [comment]
I'm flattered. :)
(I sometimes surprise myself when procrastinating with univ projects ^^)

**Comment by AdrieanKhisbe** [comment]
Hey @skuro, I hope you had a nice beginning of the year.
Did you have yet the opportunity to check the changes? I guess you might be busy, but let me know 
regards :)

**Comment by skuro** [comment]
Hi Adriean,

I actually gave it a shot last weekend, and something must be terribly
wrong with my environment, which now gives me tons of issues which I
honestly don't get. For instance, when I run the plugin in a debug session,
it miserably fail to load icons and to make the syntax highlight to work.
The same goes when I install the plugin locally. I see it fails to find
stuff on the classpath (e.g. the icons) even if they're properly packaged
in the JAR. I'm using Idea 13, BTW.

Do you recognize any of the above issues? I'm pretty new to plugin
development myself, and I might be doing something very stupid on my side.
I will try again to make it to work, and now I have a new instance of Idea
14 where to try. Will let you know if things get better.

Thanks,
c.

Il giorno Thu Jan 22 2015 at 7:59:49 AM AdrieanKhisbe <
notifications@github.com> ha scritto:

**Comment by AdrieanKhisbe** [comment]
I'm also new to plugin development on idea, 
might be maybe coming from the way I compile it using Idea 14.
(because I didn't touch anything about icon declaration, just moved them in a ressource directory, that is copied where they where in the jar)

Tell me if you have the same issue on Idea 14. :)
could you provide me the stack traces ?

**Comment by AdrieanKhisbe** [comment]
Whie trying to set up dev environmnet on new machine, I realised I didn't push all the `.idea`files necessary to have a *ready to go* repo.

Check it out, and tell me if you can `Prepare plugin for deployment` and if this is working.

thanks in advance :)

**Comment by Trevoke** [comment]
I'm pretty psyched about this, and I hope it gets merged in! :)

**Comment by AdrieanKhisbe** [comment]
@Trevoke Me too ;)

I just started working on the grammar, don't know yet where this will lead the plugin ^^

https://github.com/AdrieanKhisbe/org4idea/tree/grammar

**Comment by skuro** [comment]
Hi Aldric,

a million times sorry, I have been procrastinating this for just too long.

Here's what I'm going to do: I will merge your changes immediately and push
the plugin build. As you said you're using it for long time now, and
whether or not my issues are local to my installation or not, I'd rather
have bug reports than letting this wait any longer :-)

Thanks again!
c.

Il giorno Sat Feb 21 2015 at 7:39:14 PM Aldric Giacomoni <
notifications@github.com> ha scritto:

**Comment by skuro** [comment]
"You plug-in has been submitted for moderation, and will be processed within two working days."

Will be downloadable pretty soon :-) Thanks @AdrieanKhisbe!

**Comment by AdrieanKhisbe** [comment]
Perfect!! :smile:

**Comment by AdrieanKhisbe** [comment]
We should perform some tagging, of the version, release with the `maj.min.pat` (already assumed there would be create in the `Changelog.md`) 

You'll know better than me which is 0.1.0 ish and 0.1.1 :)

**Comment by AdrieanKhisbe** [comment]
[**Online !!!**](https://plugins.jetbrains.com/plugin/7095) :D

**Comment by skuro** [comment]
Good stuff, thanks again @AdrieanKhisbe!

**Pull request merged**
